services:

  gateway:
    build:
      context: ./gateway
    ports:
      - "80:80"
    restart: always
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - order
      - user
      - restaurant
  
  user:
    build:
      context: ./services/user
    expose:
      - "5000:5000"
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - mongo

  order:
    build:
      context: ./services/order
    expose:
      - "5000:5000"
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - mongo
  
  restaurant:
    build:
      context: ./services/restaurant
    expose:
      - "5000:5000"
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - mongo

  mongo:
    image: mongo
    expose:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --quiet --logpath /dev/null