services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - order

  auth:
    build:
      context: ./services/auth
    expose:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo
    deploy:
      replicas: 2
    develop:
      watch:
        - action: rebuild
          path: ./services/auth
    
  order:
    build:
      context: ./services/order
    expose:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo
    deploy:
      replicas: 2
    develop:
      watch:
        - action: rebuild
          path: ./services/order


  mongo:
    image: mongo
    expose:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --quiet --logpath /dev/null